### ISSUE TITLE
Wireless

### ISSUE THREAD

**Issue by kevindoni** [ophub/amlogic-s9xxx-openwrt#18] opened 2021-02-26 12:32 UTC
Please add wireless on stb hg680p

**Comment by ramasedang** [comment] 2021-02-26 12:40
check closed issue before request

**Comment by ophub** [comment] 2021-02-26 13:14
Duplicate of #13 
I tried to introduce this driver file a few days ago, but the test is not available, I am looking for it, sorry I can’t help you now.

**Closed** 2021-02-26 14:22 UTC
